import catalogue from "./national-mountains.json";
import type { MountainDifficulty, Source, Trail } from "./mountains";

export type PublishedTrail = Trail & {
  difficulty: MountainDifficulty;
  difficultyMax?: MountainDifficulty;
  source: Source;
};

export type MapMountain = {
  kind?: "mountain" | "ridge";
  /** A known jump-off is used when summit coordinates are not verified. */
  coordinateType?: "jump-off";
  slug: string;
  name: string;
  location: string;
  coordinates: [number, number];
  aliases: string[];
  elevationMeters?: number;
  /** Lowest published route rating; use trails for route-specific comparisons. */
  difficulty?: MountainDifficulty;
  trails?: PublishedTrail[];
  sources: Source[];
};

// Nationwide map/list catalogue, independent of the prominent cards.
// Generated by scripts/import-mountain-catalogue.py; see docs/mountain-catalogue.md.
export const mapMountains = catalogue as MapMountain[];

export function mountainDifficultyLabel(mountain: MapMountain): string {
  if (!mountain.trails?.length) return "No published route rating found";
  const minimum = Math.min(...mountain.trails.map((trail) => trail.difficulty));
  const maximum = Math.max(...mountain.trails.map((trail) => trail.difficultyMax ?? trail.difficulty));
  return minimum === maximum ? `Route difficulty ${minimum}/9` : `Route difficulty ${minimum}\u2013${maximum}/9`;
}
